# Site settings
title: CodeFirst:Girls - Advanced Ruby
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cfg-ruby.tk" # the base hostname & protocol for your site
cfg_homepage: "http://www.codefirstgirls.org.uk/"
twitter_username: CodeFirstGirls

# Build settings
markdown: kramdown
