# Site settings
title: CodeFirst:Girls - Advanced Ruby
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cfg-ruby.tk" # the base hostname & protocol for your site
cfg_homepage: "http://www.codefirstgirls.org.uk/"
twitter_username: CodeFirstGirls

# Build settings
markdown: kramdown
exclude: ["Rakefile", "css/wkhtmltopdf.css"]

# Default on GitHub Pages
safe: true
lsi: false

collections:
  # `sections` must come before `sessions` here to be properly rendered
  sections:
    output: false

  sessions:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: sessions
    values:
      layout: session
